import React from 'react';
import { FlowchartNode, NodeType, Equipment, EquipmentModel } from './types';
import { SignalSlashIcon, WifiIcon, QuestionMarkCircleIcon, WrenchScrewdriverIcon, CheckCircleIcon, LightBulbIcon, ExclamationTriangleIcon } from './components/Icons';

export const ONU_MODELS_DATA: EquipmentModel[] = [
  { name: 'FiberHome AN5506-01-A 1GE BRIDGE MINI UPC', imageUrl: 'https://i.imgur.com/Kz8VzYk.png' },
  { name: 'F. ONU GPON WIFI AC FD504GW-DG-Z410 4GE 2.4/5G', imageUrl: 'https://i.imgur.com/2Q4gq3d.png' },
  { name: 'F. ONU GPON/EPON BRIDGE 1GE 10/100/1000 V2801SG UPC', imageUrl: 'https://i.imgur.com/p8g8t6r.png' }
];

export const ROUTER_MODELS_DATA: EquipmentModel[] = [
  { name: 'TP-LINK ARCHER C5 W PROVEDOR ROUTER AC1200 DUAL BAND GIGA - BRANCO', imageUrl: 'https://i.imgur.com/W3sD9h6.png' },
  { name: 'ROTEADOR WIRE 1200MBS AC 1200 EC220 TP-LINK 4 ANTENAS', imageUrl: 'https://i.imgur.com/l7xP6Uf.png' },
  { name: 'TP-LINK EC230-G1 ROTEADOR GIGABIT DUAL BAND AC1350', imageUrl: 'https://i.imgur.com/nJ5J0qY.png' },
  { name: 'ROTEADOR WIRELESS W6-1500 INTELBRAS', imageUrl: 'https://i.imgur.com/4zYf7g2.png' }
];

export const FLOWCHART_DATA: { [key: string]: FlowchartNode } = {
  'start': {
    id: 'start',
    type: NodeType.START,
    title: 'Início do Atendimento',
    text: 'Clique em "Iniciar Atendimento" para começar o diagnóstico.',
    icon: LightBulbIcon
  },
  'problem_selection': {
    id: 'problem_selection',
    type: NodeType.QUESTION,
    title: 'Identificação do Problema',
    text: 'Qual é o problema principal relatado pelo cliente?',
    icon: QuestionMarkCircleIcon,
    options: [
      { text: 'Sem conexão à internet', nextNodeId: 'check_onu_lights' },
      { text: 'Internet lenta', nextNodeId: 'slow_internet_ask_wired_test' },
      { text: 'Wi-Fi não funciona', nextNodeId: 'wifi_ask_initial_problem' },
      { text: 'Internet caindo (quedas constantes)', nextNodeId: 'internet_dropping_start' },
      { text: 'Problemas com IPTV (TV)', nextNodeId: 'iptv_start' },
    ],
  },
  'check_onu_lights': {
    id: 'check_onu_lights',
    type: NodeType.QUESTION,
    title: 'Verificar LEDs da ONU',
    // Fix: Replaced JSX with React.createElement because this is a .ts file, not a .tsx file.
    // This resolves numerous parsing errors.
    text: React.createElement('div', null,
      React.createElement('p', { className: "mb-2" }, "Peça ao cliente para verificar as luzes no aparelho da HNET (ONU)."),
      React.createElement('p', { className: "font-semibold" }, 'A luz "LOS" está vermelha ou piscando em vermelho?'),
      React.createElement('img', { src: "https://i.imgur.com/O8O3LaR.png", alt: "Exemplo de ONU com luzes", className: "my-4 rounded-lg shadow-sm" })
    ),
    icon: ExclamationTriangleIcon,
    options: [
      { text: 'Sim, está vermelha/piscando', nextNodeId: 'los_red_solution', style: 'danger' },
      { text: 'Não, está apagada ou verde', nextNodeId: 'check_pon_light' },
    ],
  },
  'los_red_solution': {
    id: 'los_red_solution',
    type: NodeType.SOLUTION,
    title: 'Problema na Fibra Óptica',
    text: 'A luz LOS vermelha indica um problema físico com o sinal da fibra. Pode ser um rompimento ou desconexão no poste, ou problema no conector. É necessário agendar uma visita técnica.',
    icon: SignalSlashIcon,
  },
  'check_pon_light': {
    id: 'check_pon_light',
    type: NodeType.QUESTION,
    title: 'Verificar LED "PON" (ou "Link")',
    text: 'A luz "PON" (ou "Link") está acesa e verde (sem piscar)?',
    icon: QuestionMarkCircleIcon,
    options: [
      { text: 'Sim, está verde e fixa', nextNodeId: 'check_router' },
      { text: 'Não, está piscando ou apagada', nextNodeId: 'reboot_onu' },
    ],
  },
  'reboot_onu': {
    id: 'reboot_onu',
    type: NodeType.ACTION,
    title: 'Reiniciar a ONU',
    text: 'Instrua o cliente a remover o cabo de energia da ONU, aguardar 30 segundos e reconectar. Aguarde o aparelho reiniciar completamente (cerca de 3-5 minutos).',
    icon: WrenchScrewdriverIcon,
    nextNodeId: 'check_pon_light_after_reboot',
  },
  'check_pon_light_after_reboot': {
    id: 'check_pon_light_after_reboot',
    type: NodeType.QUESTION,
    title: 'Verificar Novamente Após Reiniciar',
    text: 'Após reiniciar a ONU, a luz "PON" (ou "Link") ficou verde e fixa?',
    icon: QuestionMarkCircleIcon,
    options: [
      { text: 'Sim, agora está verde e fixa', nextNodeId: 'check_router' },
      { text: 'Não, continua piscando ou apagada', nextNodeId: 'pon_issue_solution' },
    ],
  },
  'pon_issue_solution': {
    id: 'pon_issue_solution',
    type: NodeType.SOLUTION,
    title: 'Problema de Autenticação',
    text: 'Se a luz PON não estabiliza, pode haver um problema de provisionamento ou autenticação do equipamento na nossa central. Verifique o status do cliente no sistema principal e, se necessário, escale para o Nível 2.',
    icon: SignalSlashIcon,
  },
  'check_router': {
    id: 'check_router',
    type: NodeType.QUESTION,
    title: 'Verificar Conexão com Roteador',
    text: 'O cliente utiliza um roteador particular ou o da HNET? Verifique se o cabo de rede está firmemente conectado da porta LAN da ONU para a porta WAN (ou Internet) do roteador.',
    icon: WifiIcon,
    options: [
      { text: 'Cabo conectado, vamos testar', nextNodeId: 'reboot_router' },
      { text: 'Cabo estava solto', nextNodeId: 'reconnect_cable_solution' },
    ],
  },
   'reconnect_cable_solution': {
    id: 'reconnect_cable_solution',
    type: NodeType.SOLUTION,
    title: 'Problema de Conexão Física Resolvido',
    text: 'Após reconectar o cabo, a internet deve voltar. Peça ao cliente para testar a conexão em um dispositivo.',
    icon: CheckCircleIcon,
  },
  'reboot_router': {
    id: 'reboot_router',
    type: NodeType.ACTION,
    title: 'Reiniciar o Roteador',
    text: 'Agora, instrua o cliente a remover o cabo de energia do roteador, aguardar 30 segundos e reconectar. Aguarde o aparelho reiniciar.',
    icon: WrenchScrewdriverIcon,
    nextNodeId: 'final_check_solution',
  },
  'final_check_solution': {
    id: 'final_check_solution',
    type: NodeType.SOLUTION,
    title: 'Teste a Conexão',
    text: 'Após reiniciar a ONU e o Roteador, a conexão deve ser restabelecida. Peça ao cliente para testar o acesso à internet em um computador ou celular.',
    icon: CheckCircleIcon,
  },
  // --- DETAILED SLOW INTERNET FLOW ---
  'slow_internet_ask_wired_test': {
    id: 'slow_internet_ask_wired_test',
    type: NodeType.QUESTION,
    title: 'Diagnóstico de Lentidão',
    text: 'A lentidão ocorre em todos os dispositivos (conectados via cabo e Wi-Fi) ou apenas nos dispositivos conectados ao Wi-Fi?',
    icon: QuestionMarkCircleIcon,
    options: [
      { text: 'Apenas no Wi-Fi', nextNodeId: 'wifi_slow_check_position' },
      { text: 'Em ambos / Só uso cabo', nextNodeId: 'slow_internet_wired_speedtest' },
    ],
  },
  'slow_internet_wired_speedtest': {
    id: 'slow_internet_wired_speedtest',
    type: NodeType.ACTION,
    title: 'Teste de Velocidade via Cabo',
    text: 'Por favor, instrua o cliente a conectar um computador diretamente ao roteador com um cabo de rede, acessar um site de teste de velocidade (ex: speedtest.net ou fast.com) e realizar o teste.',
    icon: WrenchScrewdriverIcon,
    nextNodeId: 'slow_internet_compare_speed',
  },
  'slow_internet_compare_speed': {
    id: 'slow_internet_compare_speed',
    type: NodeType.QUESTION,
    title: 'Comparar Velocidade',
    text: 'A velocidade medida no teste de cabo está significativamente abaixo do plano contratado pelo cliente?',
    icon: QuestionMarkCircleIcon,
    options: [
      { text: 'Sim, muito abaixo', nextNodeId: 'slow_internet_reboot_router_and_onu' },
      { text: 'Não, está normal no cabo', nextNodeId: 'wifi_slow_check_position' },
    ],
  },
  'slow_internet_reboot_router_and_onu': {
    id: 'slow_internet_reboot_router_and_onu',
    type: NodeType.ACTION,
    title: 'Reiniciar ONU e Roteador',
    text: 'Instrua o cliente a reiniciar primeiro a ONU (desligar, esperar 30s, ligar) e, após a ONU estabilizar as luzes, fazer o mesmo com o roteador. Depois, refaça o teste de velocidade no cabo.',
    icon: WrenchScrewdriverIcon,
    nextNodeId: 'slow_internet_retest_speed',
  },
  'slow_internet_retest_speed': {
    id: 'slow_internet_retest_speed',
    type: NodeType.QUESTION,
    title: 'Verificar Velocidade Pós-Reinicialização',
    text: 'Após reiniciar os equipamentos, a velocidade no cabo melhorou?',
    icon: QuestionMarkCircleIcon,
    options: [
      { text: 'Sim, melhorou', nextNodeId: 'slow_internet_solved' },
      { text: 'Não, continua lenta', nextNodeId: 'slow_internet_schedule_visit' },
    ],
  },
  'slow_internet_solved': {
    id: 'slow_internet_solved',
    type: NodeType.SOLUTION,
    title: 'Problema de Lentidão Resolvido',
    text: 'A reinicialização dos equipamentos resolveu o problema de lentidão. O atendimento pode ser finalizado.',
    icon: CheckCircleIcon,
  },
  'slow_internet_schedule_visit': {
    id: 'slow_internet_schedule_visit',
    type: NodeType.SOLUTION,
    title: 'Agendar Visita Técnica',
    text: 'A lentidão persiste mesmo no cabo após os procedimentos. Pode ser um problema na rede externa, no provisionamento ou no equipamento. Agende uma visita técnica.',
    icon: SignalSlashIcon,
  },
  // --- DETAILED WIFI FLOW ---
  'wifi_ask_initial_problem': {
    id: 'wifi_ask_initial_problem',
    type: NodeType.QUESTION,
    title: 'Diagnóstico de Wi-Fi',
    text: 'Qual é o problema específico com o Wi-Fi?',
    icon: WifiIcon,
    options: [
      { text: 'O nome da rede (SSID) não aparece', nextNodeId: 'wifi_ssid_not_visible' },
      { text: 'Conecta, mas não navega ou está muito lento', nextNodeId: 'wifi_slow_check_position' },
      { text: 'Não conecta (erro de senha/autenticação)', nextNodeId: 'wifi_password_issue' },
    ],
  },
  'wifi_ssid_not_visible': {
    id: 'wifi_ssid_not_visible',
    type: NodeType.QUESTION,
    title: 'Rede Wi-Fi Não Visível',
    text: 'Peça ao cliente para verificar o roteador. A luz que indica o Wi-Fi (geralmente com um símbolo de antena) está acesa?',
    icon: QuestionMarkCircleIcon,
    options: [
      { text: 'Sim, a luz está acesa', nextNodeId: 'wifi_reboot_for_ssid' },
      { text: 'Não, está apagada', nextNodeId: 'wifi_check_button_solution' },
    ],
  },
  'wifi_check_button_solution': {
    id: 'wifi_check_button_solution',
    type: NodeType.SOLUTION,
    title: 'Verificar Botão Wi-Fi',
    text: 'Alguns roteadores têm um botão físico para ligar/desligar o Wi-Fi. Peça para o cliente procurar e pressionar este botão. Se a luz acender, a rede deve aparecer.',
    icon: LightBulbIcon,
  },
  'wifi_reboot_for_ssid': {
    id: 'wifi_reboot_for_ssid',
    type: NodeType.ACTION,
    title: 'Reiniciar Roteador',
    text: 'Instrua o cliente a reiniciar o roteador (desligar da tomada, esperar 30s, ligar). Aguarde 2-3 minutos e peça para verificar se a rede apareceu.',
    icon: WrenchScrewdriverIcon,
    nextNodeId: 'wifi_ssid_visible_after_reboot',
  },
  'wifi_ssid_visible_after_reboot': {
    id: 'wifi_ssid_visible_after_reboot',
    type: NodeType.QUESTION,
    title: 'Verificar Visibilidade da Rede',
    text: 'Após reiniciar, a rede Wi-Fi do cliente apareceu na lista de redes do dispositivo?',
    icon: QuestionMarkCircleIcon,
    options: [
      { text: 'Sim, apareceu', nextNodeId: 'wifi_connect_test_solution' },
      { text: 'Não, continua sem aparecer', nextNodeId: 'wifi_faulty_router_solution' },
    ],
  },
  'wifi_faulty_router_solution': {
    id: 'wifi_faulty_router_solution',
    type: NodeType.SOLUTION,
    title: 'Possível Falha no Roteador',
    text: 'Se o SSID não é visível mesmo com a luz de Wi-Fi acesa e após reiniciar, o transmissor do roteador pode estar com defeito. Agende uma visita técnica para verificação ou troca.',
    icon: SignalSlashIcon,
  },
  'wifi_password_issue': {
    id: 'wifi_password_issue',
    type: NodeType.ACTION,
    title: 'Corrigir Senha',
    text: 'Instrua o cliente a usar a opção "Esquecer esta rede" no dispositivo (celular/computador) e tentar conectar novamente, digitando a senha com atenção a letras maiúsculas/minúsculas e caracteres especiais.',
    icon: WrenchScrewdriverIcon,
    nextNodeId: 'wifi_connect_test_solution',
  },
  'wifi_connect_test_solution': {
    id: 'wifi_connect_test_solution',
    type: NodeType.SOLUTION,
    title: 'Teste a Conexão',
    text: 'Ótimo! Peça ao cliente para conectar na rede e testar a navegação em algum site ou aplicativo.',
    icon: CheckCircleIcon,
  },
  'wifi_slow_check_position': {
    id: 'wifi_slow_check_position',
    type: NodeType.QUESTION,
    title: 'Verificar Posição e Obstáculos',
    text: 'O cliente está muito longe do roteador? Existem muitas paredes, lajes ou aparelhos como micro-ondas entre o dispositivo e o roteador?',
    icon: QuestionMarkCircleIcon,
    options: [
      { text: 'Sim, estou longe / com obstáculos', nextNodeId: 'wifi_proximity_solution' },
      { text: 'Não, estou perto e sem muitos obstáculos', nextNodeId: 'wifi_slow_reboot_router' },
    ],
  },
  'wifi_proximity_solution': {
    id: 'wifi_proximity_solution',
    type: NodeType.SOLUTION,
    title: 'Otimizar Sinal do Wi-Fi',
    text: 'A distância e obstáculos (paredes, espelhos, aquários) enfraquecem o sinal. Sugira que o cliente se aproxime do roteador para testar. Para melhorar a cobertura, recomende mover o roteador para um local mais alto e central na casa.',
    icon: LightBulbIcon,
  },
  'wifi_slow_reboot_router': {
    id: 'wifi_slow_reboot_router',
    type: NodeType.ACTION,
    title: 'Reiniciar Roteador',
    text: 'Vamos reiniciar o roteador. Isso pode ajudar o aparelho a selecionar um canal de Wi-Fi com menos interferência. Desligue-o da tomada, aguarde 30 segundos e ligue novamente.',
    icon: WrenchScrewdriverIcon,
    nextNodeId: 'wifi_slow_final_check',
  },
  'wifi_slow_final_check': {
    id: 'wifi_slow_final_check',
    type: NodeType.SOLUTION,
    title: 'Teste a Velocidade no Wi-Fi',
    text: 'Após reiniciar o roteador, a conexão sem fio deve melhorar. Peça para o cliente testar novamente. Se o problema de lentidão persistir apenas em locais distantes, reforce a sugestão de reposicionar o roteador ou adquirir um repetidor.',
    icon: CheckCircleIcon,
  },
  // --- INTERNET DROPPING FLOW ---
  'internet_dropping_start': {
    id: 'internet_dropping_start',
    type: NodeType.QUESTION,
    title: 'Analisar Padrão das Quedas',
    text: 'A queda de internet acontece em momentos específicos (ex: ao usar um aparelho, em certo horário) ou é totalmente aleatória?',
    icon: QuestionMarkCircleIcon,
    options: [
      { text: 'É aleatória', nextNodeId: 'internet_dropping_check_cables' },
      { text: 'Acontece em momentos específicos', nextNodeId: 'internet_dropping_specific_moments' },
    ],
  },
  'internet_dropping_specific_moments': {
    id: 'internet_dropping_specific_moments',
    type: NodeType.QUESTION,
    title: 'Investigar Causas Específicas',
    text: 'Isso pode ser causado por interferência (micro-ondas, telefone sem fio) ou sobrecarga na rede. O roteador fica perto de outros aparelhos eletrônicos? A queda acontece quando muitas pessoas ou dispositivos estão usando a internet ao mesmo tempo?',
    icon: QuestionMarkCircleIcon,
    options: [
      { text: 'Sim, pode ser uma dessas causas', nextNodeId: 'internet_dropping_interference_solution' },
      { text: 'Não, o cenário não se aplica', nextNodeId: 'internet_dropping_check_cables' },
    ],
  },
  'internet_dropping_interference_solution': {
    id: 'internet_dropping_interference_solution',
    type: NodeType.SOLUTION,
    title: 'Solução para Interferência/Sobrecarga',
    text: 'Sugira ao cliente afastar o roteador de possíveis fontes de interferência. Se o problema for sobrecarga, oriente a desconectar alguns dispositivos e observar se a conexão estabiliza. Um upgrade de plano pode ser uma solução a longo prazo.',
    icon: LightBulbIcon,
  },
  'internet_dropping_check_cables': {
    id: 'internet_dropping_check_cables',
    type: NodeType.ACTION,
    title: 'Verificar Cabos e Conexões',
    text: 'Vamos garantir que tudo está bem conectado. Peça para o cliente verificar se o cabo de fibra está bem firme na ONU, sem dobras acentuadas ou visíveis. Verifique também o cabo de rede entre a ONU e o roteador.',
    icon: WrenchScrewdriverIcon,
    nextNodeId: 'internet_dropping_reboot_all',
  },
  'internet_dropping_reboot_all': {
    id: 'internet_dropping_reboot_all',
    type: NodeType.ACTION,
    title: 'Reinicialização Completa dos Equipamentos',
    text: 'Instrua o cliente a desligar a ONU e o Roteador da tomada. Aguardar 1 minuto. Ligar APENAS a ONU e esperar todas as luzes estabilizarem (cerca de 3-5 minutos). Somente depois, ligar o Roteador e aguardar o reinício completo.',
    icon: WrenchScrewdriverIcon,
    nextNodeId: 'internet_dropping_monitor',
  },
  'internet_dropping_monitor': {
    id: 'internet_dropping_monitor',
    type: NodeType.QUESTION,
    title: 'Monitorar a Conexão',
    text: 'Após o reinício completo, a conexão parece estável?',
    icon: QuestionMarkCircleIcon,
    options: [
      { text: 'Sim, parece estável por enquanto', nextNodeId: 'internet_dropping_monitor_solution' },
      { text: 'Não, a conexão já caiu novamente', nextNodeId: 'internet_dropping_schedule_visit', style: 'danger' },
    ],
  },
  'internet_dropping_monitor_solution': {
    id: 'internet_dropping_monitor_solution',
    type: NodeType.SOLUTION,
    title: 'Monitoramento é a Solução',
    text: 'A reinicialização pode ter resolvido. Peça ao cliente para monitorar a conexão nas próximas horas. Se o problema de quedas voltar, pode ser uma instabilidade na rede externa, e ele deve entrar em contato novamente para uma verificação mais aprofundada.',
    icon: CheckCircleIcon,
  },
  'internet_dropping_schedule_visit': {
    id: 'internet_dropping_schedule_visit',
    type: NodeType.SOLUTION,
    title: 'Agendar Visita Técnica',
    text: 'A instabilidade persiste mesmo após todos os procedimentos. Isso pode indicar um problema mais complexo com o equipamento (ONU/Roteador) ou com o sinal da rede externa. É necessário agendar uma visita técnica.',
    icon: SignalSlashIcon,
  },
  // --- IPTV FLOW ---
  'iptv_start': {
    id: 'iptv_start',
    type: NodeType.QUESTION,
    title: 'Diagnóstico de IPTV',
    text: 'Qual é o problema específico com a IPTV (serviço de TV)?',
    icon: QuestionMarkCircleIcon,
    options: [
      { text: 'IPTV travando ou com imagem quadriculada', nextNodeId: 'iptv_stuttering_check_connection' },
      { text: 'Tela preta ou mensagem de "Sem Sinal"', nextNodeId: 'iptv_black_screen_check_devices' },
      { text: 'Apenas alguns canais não funcionam', nextNodeId: 'iptv_specific_channels_issue' },
      { text: 'O aplicativo da IPTV não abre ou trava', nextNodeId: 'iptv_app_issue_reboot_stb' },
    ],
  },
  'iptv_stuttering_check_connection': {
      id: 'iptv_stuttering_check_connection',
      type: NodeType.QUESTION,
      title: 'Como o Dispositivo está Conectado?',
      text: 'O problema de travamento ocorre em um decodificador (set-top box) conectado por cabo de rede ou em um dispositivo via Wi-Fi (como uma Smart TV ou celular)?',
      icon: QuestionMarkCircleIcon,
      options: [
        { text: 'Conectado via cabo de rede', nextNodeId: 'iptv_wired_reboot_all' },
        { text: 'Conectado via Wi-Fi', nextNodeId: 'iptv_wifi_stuttering_solution' },
      ],
  },
  'iptv_wifi_stuttering_solution': {
      id: 'iptv_wifi_stuttering_solution',
      type: NodeType.SOLUTION,
      title: 'Otimização do Sinal Wi-Fi para IPTV',
      text: 'Travamentos na IPTV via Wi-Fi são frequentemente causados por sinal fraco, interferência (de micro-ondas, outros roteadores) ou muitos dispositivos conectados ao mesmo tempo. Sugira ao cliente: 1. Aproximar o dispositivo do roteador. 2. Se possível, conectar o dispositivo com um cabo de rede, que é a solução mais estável para streaming.',
      icon: LightBulbIcon,
  },
  'iptv_wired_reboot_all': {
      id: 'iptv_wired_reboot_all',
      type: NodeType.ACTION,
      title: 'Reinicialização Completa',
      text: 'Instrua o cliente a desligar da tomada a ONU, o Roteador e o decodificador (set-top box) da IPTV. Aguarde 1 minuto. Ligue a ONU primeiro e espere estabilizar. Depois, o Roteador e espere estabilizar. Por último, ligue o decodificador.',
      icon: WrenchScrewdriverIcon,
      nextNodeId: 'iptv_wired_reboot_check',
  },
  'iptv_wired_reboot_check': {
      id: 'iptv_wired_reboot_check',
      type: NodeType.QUESTION,
      title: 'Verificar Após Reinicialização',
      text: 'Após reiniciar todos os equipamentos, o problema (travamento ou tela preta) persiste?',
      icon: QuestionMarkCircleIcon,
      options: [
        { text: 'Sim, persiste', nextNodeId: 'iptv_schedule_visit', style: 'danger' },
        { text: 'Não, o problema foi resolvido', nextNodeId: 'iptv_solved_reboot' },
      ],
  },
  'iptv_schedule_visit': {
      id: 'iptv_schedule_visit',
      type: NodeType.SOLUTION,
      title: 'Agendar Visita Técnica',
      text: 'O problema persiste mesmo com conexão via cabo e após a reinicialização completa. Pode ser um problema de provisionamento do serviço de IPTV, no decodificador ou instabilidade na rede externa. Agende uma visita técnica.',
      icon: SignalSlashIcon,
  },
  'iptv_solved_reboot': {
      id: 'iptv_solved_reboot',
      type: NodeType.SOLUTION,
      title: 'Problema Resolvido com Reinicialização',
      text: 'A reinicialização dos equipamentos corrigiu a falha. O atendimento pode ser finalizado.',
      icon: CheckCircleIcon,
  },
  'iptv_black_screen_check_devices': {
      id: 'iptv_black_screen_check_devices',
      type: NodeType.ACTION,
      title: 'Verificar Conexões Físicas (TV/Decodificador)',
      text: 'Peça ao cliente para verificar os seguintes pontos: 1. O decodificador (set-top box) está com a luz de ligado acesa? 2. O cabo HDMI está firmemente conectado na TV e no decodificador? 3. A TV está na entrada correta (ex: HDMI 1, HDMI 2)?',
      icon: WrenchScrewdriverIcon,
      nextNodeId: 'iptv_black_screen_check_result',
  },
  'iptv_black_screen_check_result': {
      id: 'iptv_black_screen_check_result',
      type: NodeType.QUESTION,
      title: 'Verificar Resultado',
      text: 'Após verificar os cabos e a entrada da TV, a imagem apareceu?',
      icon: QuestionMarkCircleIcon,
      options: [
        { text: 'Sim, a imagem voltou', nextNodeId: 'iptv_solved_cable_issue' },
        { text: 'Não, continua sem imagem', nextNodeId: 'iptv_wired_reboot_all' },
      ],
  },
  'iptv_solved_cable_issue': {
      id: 'iptv_solved_cable_issue',
      type: NodeType.SOLUTION,
      title: 'Problema de Conexão Física Resolvido',
      text: 'O problema era um cabo mal conectado ou a TV estava na entrada HDMI errada. A imagem foi restabelecida.',
      icon: CheckCircleIcon,
  },
  'iptv_specific_channels_issue': {
      id: 'iptv_specific_channels_issue',
      type: NodeType.SOLUTION,
      title: 'Problema em Canais Específicos',
      text: 'Quando apenas alguns canais apresentam falha, geralmente indica um problema na fonte de transmissão (headend) e não na conexão do cliente. Anote os canais com problema e escale para o Nível 2 da equipe de TV para verificação.',
      icon: SignalSlashIcon,
  },
  'iptv_app_issue_reboot_stb': {
      id: 'iptv_app_issue_reboot_stb',
      type: NodeType.ACTION,
      title: 'Reiniciar Decodificador (Set-Top Box)',
      text: 'Peça para o cliente desligar o decodificador da tomada, aguardar 30 segundos e ligar novamente. Se o problema persistir e o sistema permitir, instrua o cliente a procurar nas configurações a opção de "Limpar Cache" do aplicativo da IPTV.',
      icon: WrenchScrewdriverIcon,
      nextNodeId: 'iptv_app_issue_solution',
  },
  'iptv_app_issue_solution': {
      id: 'iptv_app_issue_solution',
      type: NodeType.SOLUTION,
      title: 'Monitorar o Aplicativo',
      text: 'Após a reinicialização, o aplicativo deve funcionar normalmente. Se o travamento do aplicativo for recorrente, pode ser necessário uma atualização de firmware do decodificador, o que exigiria uma visita técnica.',
      icon: CheckCircleIcon,
  },
};

export const INITIAL_EQUIPMENT: Equipment[] = [
  {
    id: 1,
    type: 'ONU',
    model: ONU_MODELS_DATA[0].name,
    status: 'Online',
    notes: '',
  },
  {
    id: 2,
    type: 'Roteador',
    model: ROUTER_MODELS_DATA[0].name,
    status: 'Online',
    notes: '',
  },
];